info:
  contact: {}
  description: This is a sample Server pets
  title: ToDoList API
  version: 0.0.1
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: f
    name: FanOne
    type: apiKey
swagger: "2.0"
